export const GET_EVALUATORS = "GET_EVALUATORS";
export const SELECT_EVALUATOR = "SELECT_EVALUATOR";
export const SELECT_INPUT_MIME_TYPE = "SELECT_INPUT_MIME_TYPE";
export const CHANGE_VALUE_CURRENT_VARIABLE = "CHANGE_VALUE_CURRENT_VARIABLE";
export const CHANGE_EXPRESSION = "CHANGE_EXPRESSION";
export const UPDATE_SELECTED_PROJECT = "UPDATE_SELECTED_PROJECT";

export const UPDATE_LAST_OUTPUT = "UPDATE_LAST_OUTPUT";
export const EVALUATION_STARTED = "EVALUATION_STARTED";
export const EVALUATION_END = "EVALUATION_END";

export const UPDATE_VARIABLE = "UPDATE_VARIABLE";
export const REMOVE_VARIABLE = "REMOVE_VARIABLE";
export const CREATE_VARIABLE = "CREATE_VARIABLE";
export const SELECT_VARIABLE = "SELECT_VARIABLE";

export const SAVE_COLLECTION = "SAVE_COLLECTION";
export const SELECT_LAB = "SELECT_LAB";
export const DELETE_COLLECTION = "DELETE_COLLECTION";
export const DELETE_LAB = "DELETE_LAB";

export const CREATE_COLLECTION = "CREATE_COLLECTION";
export const CREATE_LAB = "CREATE_LAB";

export const RENAME_COLLECTION = "RENAME_COLLECTION";
export const RENAME_LAB = "RENAME_LAB";
